// swift-tools-version: 6.0
import PackageDescription

let package = Package(
    name: "SwiftOpus",
    platforms: [
        .iOS(.v17),
        .macOS(.v14),
        .tvOS(.v17),
        .watchOS(.v10),
        .visionOS(.v1),
    ],
    products: [
        .library(name: "SwiftOpus", targets: ["SwiftOpus"]),
        .library(name: "COpus", targets: ["COpus"]),
    ],
    targets: [
        .target(
            name: "COpus",
            path: "Sources/COpus/opus",
            exclude: [
                "AUTHORS",
                "autogen.sh",
                "autogen.bat",
                "celt_headers.mk",
                "celt_sources.mk",
                "celt/arm",
                "celt/dump_modes",
                "celt/mips",
                "celt/meson.build",
                "celt/opus_custom_demo.c",
                "celt/tests",
                "celt/x86",
                "ChangeLog",
                "cmake",
                "CMakeLists.txt",
                "configure.ac",
                "create_opus_data.sh",
                "COPYING",
                "doc",
                "dnn",
                "include/meson.build",
                "LICENSE_PLEASE_READ.txt",
                "lpcnet_headers.mk",
                "lpcnet_sources.mk",
                "m4",
                "Makefile.am",
                                "Makefile.unix",
                "meson_options.txt",
                "meson.build",
                "meson",
                "NEWS",
                "opus_headers.mk",
                "opus_sources.mk",
                "opus-uninstalled.pc.in",
                "opus.m4",
                "opus.pc.in",
                "README.draft",
                "README",
                "releases.sha2",
                "scripts",
                "silk_headers.mk",
                "silk_sources.mk",
                "silk/arm",
                "silk/fixed",
                "silk/fixed/x86",
                "silk/meson.build",
                "silk/float/x86",
                "silk/mips",
                "silk/tests",
                "silk/x86",
                "silk/xtensa",
                "src/meson.build",
                "src/opus_compare.c",
                "src/opus_demo.c",
                "src/repacketizer_demo.c",
                "src/qext_compare.c",
                "tests",
                "tar_list.txt",
                "training",
                "update_version",
                            ],
            publicHeadersPath: "include",
            cSettings: [
                .headerSearchPath("."),
                .headerSearchPath("celt"),
                .headerSearchPath("silk"),
                .headerSearchPath("silk/float"),
                .define("OPUS_BUILD"),
                .define("VAR_ARRAYS", to: "1"),
                .define("FLOATING_POINT"),
                .define("HAVE_DLFCN_H", to: "1"),
                .define("HAVE_INTTYPES_H", to: "1"),
                .define("HAVE_LRINT", to: "1"),
                .define("HAVE_LRINTF", to: "1"),
                .define("HAVE_MEMORY_H", to: "1"),
                .define("HAVE_STDINT_H", to: "1"),
                .define("HAVE_STDLIB_H", to: "1"),
                .define("HAVE_STRING_H", to: "1"),
                .define("HAVE_STRINGS_H", to: "1"),
                .define("HAVE_SYS_STAT_H", to: "1"),
                .define("HAVE_SYS_TYPES_H", to: "1"),
                .define("HAVE_UNISTD_H", to: "1"),
            ]
        ),
        .target(
            name: "SwiftOpus",
            dependencies: ["COpus"],
            path: "Sources/SwiftOpus"
        ),
        .testTarget(
            name: "SwiftOpusTests",
            dependencies: ["SwiftOpus"],
            path: "Tests/SwiftOpusTests"
        ),
    ]
)
